### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by PaulGlorioso** [PaulGlorioso/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Set up background using CSS
- [x] Set up car spawn point 
- [x] Build subframe chassis for car
- [x] Build mainframe chassis for car
- [x] Add Tires for car
- [x] Figure out type of car (race car, sports car, f1 car, just a block?)
- [x] Add body for car (based of type)
- [x] Additional features for car (spoilers, color, motor)
