### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by PaulGlorioso** [PaulGlorioso/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Add CSS rulesets for each direction the car will be facing
- [x] Add a listen event for when first directional key is pressed to turn that direction
- [x] Add listen event for second direction
- [x] Add listen event for third direction
- [x] Add listen event for forth direction
- [x] Double check all work
- [x] Clear out any unused CSS rules and any unnecessary code like comments
- [x] Triple check work
