### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by PaulGlorioso** [PaulGlorioso/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add new object to track which way the car is facing as well as its current position on screen with the parameters of x and y.
- [x] Change the car's position to absolute
- [x] Add an event listener that that recognizes when the space key is pressed down. 
- [x] Increment the car's position to the right with setInterval method
